name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    needs: [lint, test]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Run prep
      run: npm run prep

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build Next.js
      run: pnpm run build

    - name: Setup WebOS
      run: pnpm run setup-webos

    - name: Build WebOS
      run: pnpm run build-webos

    - name: Package WebOS
      run: pnpm run package-webos

    - name: Upload WebOS IPK
      uses: actions/upload-artifact@v4
      with:
        name: webos-app
        path: dist/*.ipk
        if-no-files-found: error

    - name: Upload Next.js build
      uses: actions/upload-artifact@v4
      with:
        name: next-build
        path: .next
        if-no-files-found: error 